image: openjdk:11-jdk

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  paths:
    - .gradle

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test
  - check
  - deploy

# Build
build:
  stage: build
  tags:
    - dockerex
  script: ./gradlew --build-cache assemble
  artifacts:
    paths:
      - target/
    expire_in: 1 day

# Tests
test-root:
  stage: test
  tags:
    - dockerex
  script: "./gradlew :test"

test-cassandra:
  stage: test
  tags:
    - dockerex
  image: openjdk:8-jdk
  script: "./gradlew titanccp-common-cassandra:test"

test-kafka:
  stage: test
  tags:
    - dockerex
  script: "./gradlew titanccp-common-kafka:test"

# Check Root
checkstyle-root:
  stage: check
  tags:
    - dockerex
  script: ./gradlew :checkstyle

pmd-root:
  stage: check
  tags:
    - dockerex
  script: ./gradlew :pmd

spotbugs-root:
  stage: check
  tags:
    - dockerex
  script: ./gradlew :spotbugs

# Check Cassandra
checkstyle-cassandra:
  stage: check
  tags:
    - dockerex
  image: openjdk:8-jdk
  script: ./gradlew titanccp-common-cassandra:checkstyle

pmd-cassandra:
  stage: check
  tags:
    - dockerex
  image: openjdk:8-jdk
  script: ./gradlew titanccp-common-cassandra:pmd

spotbugs-cassandra:
  stage: check
  tags:
    - dockerex
  image: openjdk:8-jdk
  script: ./gradlew titanccp-common-cassandra:spotbugs

# Check Kafka
checkstyle-kafka:
  stage: check
  tags:
    - dockerex
  script: ./gradlew titanccp-common-kafka:checkstyle

pmd-kafka:
  stage: check
  tags:
    - dockerex
  script: ./gradlew titanccp-common-kafka:pmd

spotbugs-kafka:
  stage: check
  tags:
    - dockerex
  script: ./gradlew titanccp-common-kafka:spotbugs

# Deploy
deploy:
  stage: deploy
  tags:
    - dockerex
  script: ./gradlew publish -PsonatypeUsername=$OSSRH_JIRA_USERNAME -PsonatypePassword=$OSSRH_JIRA_PASSWORD
  only:
    refs:
      - master
    variables:
      - $OSSRH_JIRA_PASSWORD
      - $OSSRH_JIRA_USERNAME
