image: openjdk:11-jdk

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  paths:
    - .gradle

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test
  - check
  - deploy

# Build
build:
  stage: build
  tags:
    - dockerex
  script: ./gradlew --build-cache assemble
  artifacts:
    paths:
      - build/libs
      - titanccp-common-cassandra/build/libs
      - titanccp-common-kafka/build/libs
    expire_in: 1 day

# Tests
test-root:
  stage: test
  tags:
    - dockerex
  script: "./gradlew :test"
  artifacts:
    reports:
      junit: build/test-results/test/**/TEST-*.xml
    when: on_failure
    expire_in: 1 day

test-cassandra:
  stage: test
  tags:
    - dockerex
  image: openjdk:8-jdk
  script: "./gradlew titanccp-common-cassandra:test"
  artifacts:
    reports:
      junit: titanccp-common-cassandra/build/test-results/test/**/TEST-*.xml
    when: on_failure
    expire_in: 1 day

test-kafka:
  stage: test
  tags:
    - dockerex
  script: "./gradlew titanccp-common-kafka:test"
  artifacts:
    reports:
      junit: titanccp-common-kafka/build/test-results/test/**/TEST-*.xml
    when: on_failure
    expire_in: 1 day

# Checks
.checkstyle:
  stage: check
  tags:
    - dockerex
  script: ./gradlew --continue :checkstyle titanccp-common-cassandra:checkstyle titanccp-common-kafka:checkstyle
  artifacts:
    paths:
      - build/reports/checkstyle/main.html
      - titanccp-common-cassandra/build/reports/checkstyle/main.html
      - titanccp-common-kafka/build/reports/checkstyle/main.html
    when: on_failure
    expire_in: 1 day

.pmd:
  stage: check
  tags:
    - dockerex
  script: ./gradlew --continue :pmd titanccp-common-cassandra:pmd titanccp-common-kafka:pmd
  artifacts:
    paths:
      - build/reports/pmd/*.html
      - titanccp-common-cassandra/build/reports/pmd/*.html
      - titanccp-common-kafka/build/reports/pmd/*.html
    when: on_failure
    expire_in: 1 day

.spotbugs:
  stage: check
  tags:
    - dockerex
  script: ./gradlew --continue :spotbugs titanccp-common-cassandra:spotbugs titanccp-common-kafka:spotbugs
  artifacts:
    paths:
      - build/reports/spotbugs/*.html
      - titanccp-common-cassandra/build/reports/spotbugs/*.html
      - titanccp-common-kafka/build/reports/spotbugs/*.html
    when: on_failure
    expire_in: 1 day

# Deploy
deploy:
  stage: deploy
  tags:
    - dockerex
  script: ./gradlew publish -PsonatypeUsername=$OSSRH_JIRA_USERNAME -PsonatypePassword=$OSSRH_JIRA_PASSWORD
  only:
    refs:
      - master
    variables:
      - $OSSRH_JIRA_PASSWORD
      - $OSSRH_JIRA_USERNAME
