image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s deploy/settings.xml --batch-mode --errors --fail-at-end --show-version "
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  tags:
    - dockerex
  script:
    - mvn $MAVEN_CLI_OPTS compile
  artifacts:
    paths:
      - target/


test:
  stage: test
  tags:
    - dockerex
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  tags:
    - dockerex
  script:
    - mvn $MAVEN_CLI_OPTS deploy -DskipTests=true -DperformRelease=true
  only:
    - master